### ISSUE TITLE
Exclude deprecated accounts by default?

### ISSUE THREAD

**Issue by Martronic-SA** [acsone/account-financial-reporting#18]
Should we add [('account_id.deprecated','=',False)] to the domain (and possibly a way to get them back?)

**Comment by sbidoul** [comment]
Other financial reports don't do that and I see no reason to do it in mis builder. IMO, if a move line is present, it must appear in reports. Deprecating an account is only meant to prevent further moves to be added.

Can you elaborate your use case?

**Comment by Martronic-SA** [comment]
That's because once I had deprecated accounts with blance at 0.0 that were displayed in the report.
I think this was a particular case that can easily be solved with a specific domain filter.
