### ISSUE TITLE
Store report results

### ISSUE THREAD

**Issue by Martronic-SA** [acsone/account-financial-reporting#23]
Is there a way to store the report results so it's not calculated each time it's accessed?
Maybe the kpimatrix could be stored and recomputed on refresh?

**Comment by sbidoul** [comment]
All pure accounting reports (ie AEP) should be fast enough to be refreshed interactively without problem. 
Some report based on queries on other models can indeed become slow when there are many queries or columns. 

Could flesh out a little bit how this store/cache would work as an issue in https://github.com/oca/account-financial-reporting? In the meantime I close it here.
